name = "chat"
compatibility_date = "2024-01-01"

main = "src/index.mjs"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" },
]

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.client.js"]
fallthrough = false

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[vars]
GithubOwner = "langningchen"
GithubRepo = "image-data"
